
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.IO;
using System.Xml;
namespace XMLPROYECTO
{
    public partial class index : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {

        }

        protected void cmdCreateXml_Click(object sender, EventArgs e)
        {
            FileStream fs = new FileStream(@"e:\ProyectoUniversidad.xml", FileMode.Create);
            XmlTextWriter w = new XmlTextWriter(fs, null);
            w.WriteStartDocument();
            w.WriteStartElement("ProyectoUniversidad");
            w.WriteComment("This file generated by the XmlTextWriter class.");
            w.WriteStartElement("Trabajador");
            w.WriteAttributeString("Codigo", "", "1");
            w.WriteAttributeString("Nombre", "", "Clari");
            w.WriteAttributeString("Area", "", "Contabilidad");
            w.WriteStartElement("Sueldo");
            w.WriteString("4900");
            w.WriteEndElement();
            w.WriteEndElement();
            w.WriteEndDocument();
            w.Close();
            lblXml.Text = @"File E:\ProyectoUniversidad.xml written succesfully.";
        }
    }
}