//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTA
    {
        public int idventa { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> total { get; set; }
    
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
